#!/usr/bin/env python3
"""
Build RNA template index for Protenix training data.

For each RNA sequence in the training data, finds template structures using
pairwise sequence alignment (placeholder method — to be replaced with more
sophisticated search like nhmmer/cmscan later).

Outputs a JSON index mapping RNA sequences to lists of template .npz file paths.

Usage:
    python build_rna_template_index.py \
        --training_data_dir /path/to/protenix_prepared \
        --rna_database_dir /path/to/rna_database \
        --output /path/to/rna_template_index.json \
        --max_templates 4

The rna_database_dir should contain pre-computed template .npz files
generated by rna_template/compute/build_rna_template_protenix.py.
"""

import argparse
import glob
import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

try:
    from Bio import pairwise2
    from Bio.pairwise2 import format_alignment
    HAS_BIOPYTHON = True
except ImportError:
    HAS_BIOPYTHON = False


def normalize_rna_sequence(seq: str) -> str:
    """Normalize RNA sequence: uppercase, T→U, keep only AGCUN."""
    seq = seq.upper().replace("T", "U")
    return "".join(c if c in "AGCUN" else "N" for c in seq)


def pairwise_identity(seq1: str, seq2: str) -> float:
    """Compute pairwise sequence identity between two RNA sequences.

    Uses simple global alignment with match=2, mismatch=-1, gap=-5/-0.5.
    Returns fraction of identical positions over aligned length.
    """
    if not seq1 or not seq2:
        return 0.0

    if HAS_BIOPYTHON:
        alignments = pairwise2.align.globalms(
            seq1, seq2,
            2.0,   # match score
            -1.0,  # mismatch penalty
            -5.0,  # gap open penalty
            -0.5,  # gap extend penalty
            one_alignment_only=True,
        )
        if not alignments:
            return 0.0
        aln = alignments[0]
        aligned_seq1, aligned_seq2 = aln.seqA, aln.seqB
        matches = sum(1 for a, b in zip(aligned_seq1, aligned_seq2) if a == b and a != "-")
        aligned = sum(1 for a, b in zip(aligned_seq1, aligned_seq2) if a != "-" and b != "-")
        return matches / max(aligned, 1)
    else:
        # Simple fallback: count matching positions at same offset
        min_len = min(len(seq1), len(seq2))
        max_len = max(len(seq1), len(seq2))
        matches = sum(1 for i in range(min_len) if seq1[i] == seq2[i])
        return matches / max(max_len, 1)


def collect_database_templates(rna_database_dir: str) -> Dict[str, List[str]]:
    """Scan the RNA database directory for template .npz files.

    Returns a mapping from template sequence to list of .npz file paths.
    Template sequences are extracted from the .npz metadata.
    """
    templates_by_seq = {}

    if not os.path.isdir(rna_database_dir):
        print(f"Warning: RNA database directory not found: {rna_database_dir}")
        return templates_by_seq

    npz_files = glob.glob(os.path.join(rna_database_dir, "**", "*template*.npz"), recursive=True)
    # Also try flat structure
    npz_files += glob.glob(os.path.join(rna_database_dir, "*.npz"))
    npz_files = list(set(npz_files))

    print(f"Found {len(npz_files)} .npz files in {rna_database_dir}")

    for npz_path in npz_files:
        try:
            data = np.load(npz_path, allow_pickle=True)
            # Try to extract query sequence
            if "query_sequence" in data:
                query_seq_arr = data["query_sequence"]
                if query_seq_arr.ndim == 0:
                    query_seq = str(query_seq_arr)
                else:
                    query_seq = "".join(str(c) for c in query_seq_arr)
            else:
                # Try to infer from aatype
                if "template_aatype" in data:
                    aatype = data["template_aatype"]
                    if aatype.ndim >= 2:
                        aatype = aatype[0]  # first template
                    id_to_base = {21: "A", 22: "G", 23: "C", 24: "U", 25: "N", 31: "-"}
                    query_seq = "".join(id_to_base.get(int(x), "N") for x in aatype)
                    query_seq = query_seq.replace("-", "")
                else:
                    continue

            query_seq = normalize_rna_sequence(query_seq)
            if len(query_seq) < 5:
                continue

            rel_path = os.path.relpath(npz_path, rna_database_dir)
            templates_by_seq.setdefault(query_seq, []).append(rel_path)

        except Exception as e:
            print(f"Warning: Failed to process {npz_path}: {e}")
            continue

    print(f"Collected templates for {len(templates_by_seq)} unique sequences")
    return templates_by_seq


def load_training_sequences(training_data_dir: str) -> Dict[str, str]:
    """Load RNA sequences from the Protenix training data.

    Reads from the bioassembly index CSV files to find RNA sequences.
    Returns a mapping from PDB ID to RNA sequence.
    """
    sequences = {}

    # Try reading from indices
    indices_dir = os.path.join(training_data_dir, "indices")
    if os.path.isdir(indices_dir):
        import csv
        for csv_file in glob.glob(os.path.join(indices_dir, "*.csv")):
            try:
                with open(csv_file, "r") as f:
                    reader = csv.DictReader(f)
                    for row in reader:
                        pdb_id = row.get("pdb_id", "")
                        mol_type = row.get("mol_type", "")
                        if mol_type == "nuc" and pdb_id:
                            sequences[pdb_id] = ""  # placeholder
            except Exception:
                continue

    # Try reading sequence-to-pdb mapping
    seq_map_path = os.path.join(training_data_dir, "rna_msa", "rna_sequence_to_pdb_chains.json")
    if os.path.exists(seq_map_path):
        with open(seq_map_path, "r") as f:
            seq_to_pdb = json.load(f)
        for seq, pdb_info in seq_to_pdb.items():
            norm_seq = normalize_rna_sequence(seq)
            if len(norm_seq) >= 5:
                sequences[norm_seq] = norm_seq

    print(f"Loaded {len(sequences)} training RNA sequences")
    return sequences


def build_index_pairwise(
    training_sequences: Dict[str, str],
    database_templates: Dict[str, List[str]],
    max_templates: int = 4,
    min_identity: float = 0.3,
) -> Dict[str, List[str]]:
    """Build template index using pairwise sequence alignment.

    PLACEHOLDER METHOD: This uses simple pairwise alignment to find templates.
    Should be replaced with nhmmer/cmscan/BLAST for production use.

    For each training sequence, finds the best-matching templates from the database
    based on sequence identity.

    Args:
        training_sequences: Mapping of sequence identifiers to sequences.
        database_templates: Mapping of database sequences to template .npz paths.
        max_templates: Maximum templates per query sequence.
        min_identity: Minimum sequence identity threshold.

    Returns:
        Index mapping training sequences to template .npz paths.
    """
    index = {}
    db_seqs = list(database_templates.keys())

    print(f"Building pairwise index: {len(training_sequences)} queries x {len(db_seqs)} targets")

    for i, (seq_key, query_seq) in enumerate(training_sequences.items()):
        if i % 100 == 0:
            print(f"  Progress: {i}/{len(training_sequences)}")

        if not query_seq or len(query_seq) < 5:
            continue

        # Score all database templates against this query
        scored_templates = []
        for db_seq in db_seqs:
            # Quick length filter: skip if length ratio is too extreme
            len_ratio = len(db_seq) / max(len(query_seq), 1)
            if len_ratio < 0.3 or len_ratio > 3.0:
                continue

            identity = pairwise_identity(query_seq, db_seq)
            if identity >= min_identity:
                for npz_path in database_templates[db_seq]:
                    scored_templates.append((identity, npz_path))

        # Sort by identity (descending) and take top max_templates
        scored_templates.sort(key=lambda x: -x[0])
        best_paths = [path for _, path in scored_templates[:max_templates]]

        if best_paths:
            index[query_seq] = best_paths

    print(f"Built index with {len(index)} sequences having templates "
          f"(out of {len(training_sequences)} total)")
    return index


def main():
    parser = argparse.ArgumentParser(
        description="Build RNA template index for Protenix training data."
    )
    parser.add_argument(
        "--training_data_dir",
        default="/inspire/ssd/project/sais-bio/public/ash_proj/data/stanford-rna-3d-folding/part2/protenix_prepared",
        help="Directory containing Protenix-prepared training data.",
    )
    parser.add_argument(
        "--rna_database_dir",
        default="/inspire/ssd/project/sais-bio/public/ash_proj/code/protenix_new/Protenix/rna_database",
        help="Directory containing pre-computed RNA template .npz files.",
    )
    parser.add_argument(
        "--output",
        default="/inspire/ssd/project/sais-bio/public/ash_proj/code/protenix_new/Protenix/rna_database/rna_template_index.json",
        help="Output JSON index path.",
    )
    parser.add_argument("--max_templates", type=int, default=4)
    parser.add_argument("--min_identity", type=float, default=0.3)
    args = parser.parse_args()

    print("=== RNA Template Index Builder (Pairwise Placeholder) ===")
    print(f"Training data: {args.training_data_dir}")
    print(f"RNA database: {args.rna_database_dir}")
    print(f"Output: {args.output}")

    # Step 1: Collect database templates
    database_templates = collect_database_templates(args.rna_database_dir)

    # Step 2: Load training sequences
    training_sequences = load_training_sequences(args.training_data_dir)

    # Step 3: Build pairwise index
    index = build_index_pairwise(
        training_sequences=training_sequences,
        database_templates=database_templates,
        max_templates=args.max_templates,
        min_identity=args.min_identity,
    )

    # Step 4: Save index
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(index, f, indent=2)

    print(f"Index saved to {args.output}")
    print(f"Total sequences with templates: {len(index)}")


if __name__ == "__main__":
    main()
